/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { LotteryWhereUniqueInput } from "../../lottery/base/LotteryWhereUniqueInput";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { ShareRecordListRelationFilter } from "../../shareRecord/base/ShareRecordListRelationFilter";

@InputType()
class SharerWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => LotteryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => LotteryWhereUniqueInput)
  @IsOptional()
  @Field(() => LotteryWhereUniqueInput, {
    nullable: true,
  })
  lottery?: LotteryWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  points?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ShareRecordListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ShareRecordListRelationFilter)
  @IsOptional()
  @Field(() => ShareRecordListRelationFilter, {
    nullable: true,
  })
  shareRecords?: ShareRecordListRelationFilter;
}

export { SharerWhereInput as SharerWhereInput };
